---

version: "3"

services:
  wospi:
    container_name: ${container_name}
    hostname: ${hostname}
    image: ${image}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CSV_DATA}:/csv_data:rw
      - ${WOSPI_CONFIG}:$HOMEDIR/config.py:r
      - ${BACKUP_DIR}:/backup:rw
      #- ${NETRC_CONFIG}:$HOMEDIR/.netrc:r
      - ${HOME}/.ssh:$HOMEDIR/.ssh:r
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/vcio:/dev/vcio
    environment:
      TAG: "${TAG}"
      HOMEDIR: ${HOMEDIR}
      CSVPATH: ${CSVPATH}
      MAILTO: ${MAILTO}
#
